### PR TITLE
Admin Documentation: fix an example

### PR DESCRIPTION
**Pull request by rumyantseva**
I'm trying to use this example and I see that admin.AdminConfig doesn't exist in the current version of qor, it seems that we need qor.Config instead.

### CODE REVIEW

**Comment by jinzhu** [comment]
@rumyantseva you should upgrade your qor to latest master

**Comment by rumyantseva** [comment]
That's funny: I have never used qor before (and I didn't have it in my GOPATH), I was just trying to follow your documentation.

Actually,`admin.AdminConfig` looks a little bit verbose but I'll propose these changes to the suitable repo, yeah.

**Comment by jinzhu** [comment]
Maybe you are using some package manager to get the code?

**Comment by rumyantseva** [comment]
Hmmm... Yeah, you're right, sorry.
I started with a raw GOPATH and tried dep later :)
Thank you! Have a nice weekend!

**Pull request closed without merging**
