### PR TITLE
Add new content on permission behaviour to Plugins/Roles Chapter.

### PR DESCRIPTION
**Pull request by sunwukonga**
I also activated the flow chart plugin for this gitbook so that I could use a visual representation to show how everything comes together.

### CODE REVIEW

**Comment by sunwukonga** [comment]
This is a png of the flow chart rendering.
flowchart-roles

**Comment by raven-chen** [comment]
Hi @sunwukonga 

Thanks for your photo. Just an update, we're super busy recently, the end of a year you know.. we need a little longer to review and merge your pull request. 

Thanks for your patient and contribution.

**Comment by sunwukonga** [comment]
Hi Raven, just checking in with you. Was there a problem you need me to address, or are you busy still?

**Comment by raven-chen** [comment]
Hi @sunwukonga 

Happy new year! Sorry for the delay. Yes. I still busy. but hopefully, I'll get some time on this later this week.

**Comment by jinzhu** [comment]
Hi @sunwukonga 

Thank you for your PR! make the document much clear!

Thank you.

**Pull request merged**
